### ISSUE TITLE
Jenkins cannot find lscm command ?

### ISSUE THREAD

**Issue by ppcat** [SonarQubeCommunity/sonar-scm-jazzrtc#8]
Hi,

Thank you very much for this plugin. I have a question about Jenkins build error when I enable this plugin. I imagine the flow is: 
1. Trigger Jenkins build
2. Checkout RTC source
3. Run sonar-scanner
4. Run this plugin
5. Auto assign issues.

There is nothing wrong from step 1 to step 3. After I enable this plugin I got error message like this:

> 12:02:20.126 INFO: Sensor CPD Block Indexer (done) | time=175ms
12:02:20.127 INFO: SCM provider for this project is: jazz
12:02:20.128 INFO: 138 files to be analyzed
12:02:20.128 DEBUG: Working directory: /mnt/btrfs/jenkins/workspace/MY_PROJECT
12:02:20.131 DEBUG: Executing: sh lscm annotate MY_PROJECT/some_file.java
12:02:20.143 INFO: 0/138 files analyzed
12:02:20.146 INFO: ------------------------------------------------------------------------
12:02:20.146 INFO: EXECUTION FAILURE
12:02:20.146 INFO: ------------------------------------------------------------------------
12:02:20.146 INFO: Total time: 24.804s
12:02:20.302 INFO: Final Memory: 58M/759M
12:02:20.302 INFO: ------------------------------------------------------------------------
12:02:20.302 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: **The jazz annotate command [sh lscm annotate MY_PROJECT/some_file.java] failed: sh: 0: Can't open lscm**

	at org.sonar.plugins.scm.jazzrtc.JazzRtcBlameCommand.blame(JazzRtcBlameCommand.java:74)
	at org.sonar.plugins.scm.jazzrtc.JazzRtcBlameCommand.blame(JazzRtcBlameCommand.java:58)
	at org.sonar.scanner.scm.ScmPublisher.publish(ScmPublisher.java:82)
	at org.sonar.scanner.phases.PublishPhaseExecutor.afterSensors(PublishPhaseExecutor.java:59)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:80)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

> 12:02:20.303 DEBUG: Execution getVersion
12:02:20.303 DEBUG: Execution stop
Build step 'Execute shell' marked build as failure

But if I try to invoke `lscm` from Shell Execute in Jenkins, it can be found!
`lscm -h`
will display:

> lscm -h
Usage: lscm [options] [command] 
Use lscm help [command] to get detailed help for a specific command
  command - Name of the command to run
 .....

Is there anyway I can use this plugin with Jenkins build ? I just want to achieve auto assign function.

Environment:
Ubuntu 14.04
SonarQube 6.3.1
sonar-scanner 3.0.3.778
jazz-scmtools 6.0.2
sonar-scm-jazzrtc plugin 1.1

Thank you very much!
Mike

**Comment by duncau1234** [comment]
Hi, you need to disable SCM command with `sonar.scm.disabled=true`, or go to administration of sonarqube and then disable it from SCM section
it functions in my job well
