### ISSUE TITLE
RTC Plugin for SonarQube Fails Intermittently

### ISSUE THREAD

**Issue by elawson1** [SonarQubeCommunity/sonar-scm-jazzrtc#9]
Using SonarQube to scan a Jenkins build integrated with RTC, the lscm annotate and blame causes job to fail intermittently. Any ideas as to why this is happening and a solution would be greatly appreciated.

**Comment by dbmeneses** [comment]
Do you have any logs or stack traces?

**Comment by chris-watts** [comment]
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 3:16.401s
ERROR: Error during SonarQube Scanner execution
INFO: Final Memory: 47M/138M
INFO: ------------------------------------------------------------------------
java.lang.IllegalStateException: The jazz annotate command [cmd /C call lscm annotate -u _serviceAccount -P somePassword Areas/SomeArea/Scripts/SomeFile.js] failed: 
    at org.sonar.plugins.scm.jazzrtc.JazzRtcBlameCommand.blame(JazzRtcBlameCommand.java:74)
    at org.sonar.plugins.scm.jazzrtc.JazzRtcBlameCommand.blame(JazzRtcBlameCommand.java:58)
    at org.sonar.scanner.scm.ScmSensor.execute(ScmSensor.java:86)
    at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
    at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
    at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
    at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
    at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
    at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
    at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
    at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
    at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
The SonarQube Scanner did not complete successfully

**Comment by dbmeneses** [comment]
Do you get any more information when running it with debug enabled (-X) ?
Do you get an error if you try running the same lscm annotate command from the console?

**Comment by chris-watts** [comment]
I am not sure where to put the -X.  I have added it as a param in the "Additional agruments" section of the "SonarQube scanner for MSBuild Being Analysis" step in my jenkins job but get no additional info when I do that.  

I have never seen an error calling directly from LSCM.

**Comment by dbmeneses** [comment]
I've checked the code and unfortunately it looks like debug won't give more information about the error.
It seems that lscm is returning an exit code != 0 and there is nothing in stderr.
Would it be possible to call lscm directly in the same machine, when it fails? It would be great to see if there is something in stdout.

**Comment by chris-watts** [comment]
The problem is that a subsequent call is successful.  We have made those calls from the same machine and they are always successful.  Even a subsequent call through jenkins/sonar usually runs successfully.

**Comment by chris-watts** [comment]
Any other thoughts?  We are geting 5-20 failures a day now.

**Comment by chris-watts** [comment]
Still failing VERY often.  Seems like it might be tied to the size of the file that is being 'annotate'd.  Always seems to fail on files that are larger than 1000 lines.    Is it possible to extend the timeout on the LSCM connection to test out the theory?

**Comment by dbmeneses** [comment]
The timeout is 60s. Do you observe it taking about 60s on a file before failing? 
You could try changing the value set to `CMD_TIMEOUT` [here](https://github.com/SonarQubeCommunity/sonar-scm-jazzrtc/blob/master/src/main/java/org/sonar/plugins/scm/jazzrtc/JazzRtcConfiguration.java#L39), compile and deploy it in SonarQube.

**Comment by jbryanmiller** [comment]
I am assisting chris-watts on this issue, I have pulled the code down and adjusted the CMD_TIMEOUT , It seems to compile fine ., but in order to port it into Jenkins, it is looking for a .hpi file ... Can you advise on the compilation process and how to get this manually installed into Jenkins please?

**Comment by henryju** [comment]
This plugin is a SonarQube plugin. It should be installed in your SonarQube server.

**Comment by jbryanmiller** [comment]
You are correct, that was my bad ... I found what seems to be the path to manually installing the plugin here - https://docs.sonarqube.org/display/SONAR/Installing+a+Plugin
However, It is not picking up my changes. I do see the mention of a "COMMERCIAL" version of SonarQube, Am i missing something other than just copying the new jar file into the plugins directory , then restarting SoanrQube?

**Comment by henryju** [comment]
Copy the plugin JAR into SQ server extensions/plugins (removing previous version of the same plugin) then restart the SQ server. This is enough to have your changes picked up during next analysis.

**Comment by chris-watts** [comment]
How do we enable debug (or trace) level logging for the plugin?  We have enabled that in SonarQube and it appears to be logging, but we can't see (or don't know where to look) to find the jazzrtc plugin log entries.

**Comment by chris-watts** [comment]
We have been able to install our version of the plugin.  We now know that the exit code we are getting back from Rational when these failures occur is a '13'.  Does that mean anything to this group?  We have opened a dialogue with IBM as well to see if they know why we would see these exit codes sporadically.

**Comment by jbryanmiller** [comment]
I have an update on our issue(elawson1 and Chris-watts)...
We have seen our failures drop off by adding the exit code: 13 to the "UNTRACKED_BLAME_RETURN_CODES" array. I am suspecting that a recent upgrade of RTC for us has introduced yet another non volatile exit code that needs to be included. Can anyone give some feedback  on these findings ? I have yet to find any intel on the Exit Code 13 but it seems to have solved our immediate issues.

**Comment by BalzGuenat** [comment]
We have the same issues when trying to annotate files that are no longer under version control (currently ignored, not so in the past). Still not completely sure if it's limited to those files but looks like it right now.

Sometimes the maven plugin crashes and sometimes it acknowledges that there is missing blame info and carries on with the build.

Is this project even still maintained?

**Comment by henryju** [comment]
@BalzGuenat The plugin is not actively maintained by SonarSource, because we have almost zero knowledge of jazzrtc, but we can assist anyone wanting to contribute.
